# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build --if-present
            - name: Test
              run: npm test
            - name: Coveralls
              uses: coverallsapp/github-action@v1.1.2
              with:
                  github-token: ${{ secrets.github_token }}
            - name: Release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
